### ISSUE TITLE
Rift initializes but the test script fails.

### ISSUE THREAD

**Issue by hashtagcpt** [mdcutone/psychxr#2]
Hi, 

First off thanks for putting this together and releasing it. I'm able to get the test lines of code to initialize the Rift. That is: 

import psychxr.ovr as ovr
ovr.capi.isHmdConnected()

checks out as True, but when I move to the demo script, I get the following string of errors pasted below. Is there something I'm missing? I'm at a bit of a loss interpreting this. I'm happy to provide more details on my hardware/software set-up if it helps.

 Thanks in advance for your help.

Best,

Chris

---
(psypy3) C:\Users\taylorpc>python D:\home\taylorcp\Dropbox\Exp\cptlab\Rift_Exp\oculus_glfw.py
07/02 12:19:18.778 {INFO}    [Kernel:Default] [CAPI] LibOVR module is located at C:\Program Files\Oculus\Support\oculus-runtime\LibOVRRT64_1.dll
07/02 12:19:18.782 {INFO}    [Client] Connected to the server running version (prod = 1).1.34.0(build = 198261) feature version = 0. Client runs version (prod = 1).1.34.0(build = 0) feature version = 0
07/02 12:19:18.801 {DEBUG}   [Kernel:Default] [HMDState] Using default profile default
07/02 12:19:18.801 {INFO}    [Kernel:Default] IAD changed to 63.7mm
07/02 12:19:18.802 {DEBUG}   [SharedMemory] Creating factory
07/02 12:19:18.802 {DEBUG}   [D3D11_CliCompositorClient] CliD3D11CompositorClient::initialize 1
07/02 12:19:18.814 {DEBUG}   [KMTSyncObject] Creating KMTHandle 0x502545e0
07/02 12:19:18.820 {DEBUG}   [D3D11_CliCompositorClient] CliD3D11CompositorClient::release 1
Traceback (most recent call last):
  File "psychxr\ovr\capi.pyx", line 88, in psychxr.ovr.capi.check_result
RuntimeError: -1006: <unknown>
Exception ignored in: 'psychxr.ovr.capi.createTextureSwapChainGL'
Traceback (most recent call last):
  File "psychxr\ovr\capi.pyx", line 88, in psychxr.ovr.capi.check_result
RuntimeError: -1006: <unknown>
07/02 12:19:18.828 {DEBUG}   [D3D11_CliCompositorClient] CliD3D11CompositorClient::initialize 1
07/02 12:19:18.836 {DEBUG}   [KMTSyncObject] Creating KMTHandle 0x50254090
Traceback (most recent call last):
07/02 12:19:18.840 {DEBUG}   [D3D11_CliCompositorClient]   File "psychxr\ovr\capi.pyx", line 88, in psychxr.ovr.capi.check_result
CliD3D11CompositorClient::release 1RuntimeError: -1006: <unknown>

Exception ignored in: 'psychxr.ovr.capi.setupMirrorTexture'
Traceback (most recent call last):
  File "psychxr\ovr\capi.pyx", line 88, in psychxr.ovr.capi.check_result
RuntimeError: -1006: <unknown>
Traceback (most recent call last):
07/02 12:19:18.850 {!ERROR!} [Kernel:Error]   File "D:\home\taylorcp\Dropbox\Exp\cptlab\Rift_Exp\oculus_glfw.py", line 293, in <module>
OVR Error:
  Code: -1004 -- ovrError_NotInitialized
  Description: Not initialized
  OVRTime: 854057.047227
  Time: 2019-02-07 12:19:18 [850:606:400]
    sys.exit(main())

  File "D:\home\taylorcp\Dropbox\Exp\cptlab\Rift_Exp\oculus_glfw.py", line 161, in main
    tex_id = capi.getTextureSwapChainBufferGL(swap_chain)
07/02 12:19:18.850 {!ERROR!} [Kernel:Error]   File "psychxr\ovr\capi.pyx", line 287, in psychxr.ovr.capi.getTextureSwapChainBufferGL
OVR Error:
  Code: -1004 -- ovrError_NotInitialized
  Description: Not initialized
  OVRTime: 854057.047706
  Time: 2019-02-07 12:19:18 [851:83:900]
  File "psychxr\ovr\capi.pyx", line 88, in psychxr.ovr.capi.check_result

RuntimeError: -1005: Null chain pointer provided.
07/02 12:19:18.850 {!ERROR!} [Kernel:Error] OVR Error:
  Code: -1005 -- ovrError_InvalidParameter
  Description: Null chain pointer provided.
  OVRTime: 854057.047857
  Time: 2019-02-07 12:19:18 [851:234:100]

**Comment by hashtagcpt** [comment]
@mdcutone  Yes, I compiled the library myself.

**Comment by mdcutone** [comment]
Which version of the API did you use? Version 0.1.4 requires Oculus SDK version 1.25. The error message seems to indicate that the client was built with a newer version, causing a service error.

**Comment by hashtagcpt** [comment]
Thanks -- I thought I used the recommended version, but I'll check on the Oculus SDK and try re-building.

**Comment by mdcutone** [comment]
I added a version checker to PsychXR 0.2 which will warn if the module was compiled with the wrong version. I also improved the installation process to make things easier.
