### ISSUE TITLE
Rift initializes and the test works. From the demo scripts libovr_minimal.py compiles but libovr_headtracking.py fails.

### ISSUE THREAD

**Issue by rahul-mitra13** [mdcutone/psychxr#6]
Hello,

Thank you for building this great tool and releasing it for general use. 

I would appreciate it if you could address a particular issue I'm having. Rift initializes fine and libovr_minimal.py compiles. However, when I run libovr_headtracking.py, nothing renders to the occulus headset and I get the following error: 

```
`C:\Users\kevin\Documents>python psychxr\demo\rift\libovr_headtracking.py
21/05 13:22:35.121 {INFO}    [Kernel:Default] [CAPI] LibOVR module is located at C:\Program Files\Oculus\Support\oculus-runtime\LibOVRRT64_1.dll
21/05 13:22:35.124 {INFO}    [Client] Connected to the server running version (prod = 1).1.37.0(build = 245188) feature version = 0. Client runs version (prod = 1).1.37.0(build = 0) feature version = 0
21/05 13:22:35.125 {DEBUG}   [Kernel:Default] [HMDState] Using default profile default
21/05 13:22:35.125 {INFO}    [Kernel:Default] IAD changed to 61.8mm
21/05 13:22:35.125 {DEBUG}   [SharedMemory] Creating factory
21/05 13:22:35.127 {DEBUG}   [D3D11_CliCompositorClient] CliD3D11CompositorClient::initialize 1
21/05 13:22:35.218 {DEBUG}   [KMTSyncObject] Creating KMTHandle 0x307e1450
21/05 13:22:35.219 {DEBUG}   [KMTSyncObject] Creating KMTHandle 0x307e1720
21/05 13:22:35.219 {DEBUG}   [KMTSyncObject] KMTHandle::Create hDevice=0x400023c0
21/05 13:22:35.219 {DEBUG}   [KMTSyncObject] KMTHandle::Create hContexts[0] = 2147486976
21/05 13:22:35.219 {DEBUG}   [KMTSyncObject] KMTHandle::Create hContexts[1] = 2147487296
**21/05 13:22:35.221 {!ERROR!} [Kernel:Error] OVR Error:
  Code: -3000 -- ovrError_Initialize
  Description: wglDXRegisterObjectNV failed
  OVRTime: 171.135913
  Time: 2019-05-21 13:22:35 [221:775:100]**

21/05 13:22:35.226 {DEBUG}   [D3D11_CliCompositorClient] CliD3D11CompositorClient::addGLRef 2
Traceback (most recent call last):
**21/05 13:22:35.227 {!ERROR!} [Kernel:Error]   File "psychxr\demo\rift\libovr_headtracking.py", line 268, in <module>
OVR Error:
  Code: -3000 -- ovrError_Initialize
  Description: wglDXRegisterObjectNV failed
  OVRTime: 171.142235
  Time: 2019-05-21 13:22:35 [228:97:100]**

    **sys.exit(main())
  File "psychxr\demo\rift\libovr_headtracking.py", line 134, in main
    _, swapIdx = getTextureSwapChainCurrentIndex(LIBOVR_TEXTURE_SWAP_CHAIN0)
  File "psychxr\libovr\_libovr.pyx", line 3365, in psychxr.libovr._libovr.getTextureSwapChainCurrentIndex
RuntimeError: Cannot get buffer ID, NULL eye buffer texture.`**
```

Is there something wrong with my installation? I initially thought it was my nvidia drivers but I'm currently running two 1070 drivers so I don't that's it. I'm also using the SDK version 1.25 so I'm not exactly sure what I'm doing wrong.

I would appreciate any help you can offer. 

Kind Regards,

**Comment by mdcutone** [comment]
The current development branch (master) is undergoing a lot of work right now and it might have issues. The demos might not be up to date with the API's capabilities.

Try using the 0.1.4 branch for Oculus API version 1.28 and try its demos. I'm looking at a release in the next week or two for version 0.2 using the latest Oculus API version, I've been holding off until I get PsychXR fully tested with the Rift S that just arrived.

**Comment by rahul-mitra13** [comment]
I figured it out. It had nothing do with the stability of the version. I had a hardware issue with the oculus  on my end. Thank you for the help!

**Comment by mdcutone** [comment]
I added a version checker to version 0.2 which warns if the wrong version was used to build the module.

**Comment by rahul-mitra13** [comment]
Awesome! Thank you!
